<?php
include("finishit.php");
xstart("0");	
	unset($_SESSION["PBNG_OS_2018_VISION"]);
	unset($_SESSION["PBNG_BR_2018_VISION"]);
	unset($_SESSION["PBNG_IP_2018_VISION"]);
	unset($_SESSION["PBNG_ID_2018_VISION"]);
	unset($_SESSION["PBNG_PHOTO_2018_VISION"]);
	unset($_SESSION["PBNG_NAME_2018_VISION"]);
	unset($_SESSION["PBNG_EMAIL_2018_VISION"]);
	unset($_SESSION["PBNG_MOBILE_2018_VISION"]);
	unset($_SESSION["PBNG_COUNTRY_2018_VISION"]);
	unset($_SESSION["PBNG_STATE_2018_VISION"]);
	unset($_SESSION["PBNG_GENDER_2018_VISION"]);
	unset($_SESSION["PBNG_POSITION_2018_VISION"]);
	unset($_SESSION["PBNG_TOKEN_2018_VISION"]);
	unset($_SESSION["PBNG_SKILL_2018_VISION"]);
	unset($_SESSION["PBNG_LL_2018_VISION"]);
	unset($_SESSION["PBNG_BN_2018_VISION"]);
	unset($_SESSION["PBNG_ACN_2018_VISION"]);
	unset($_SESSION["PBNG_ACNUMB_2018_VISION"]);
	
	finish("./","0");

?>
